/**
 * Converts an emoji string to its Twemoji CDN SVG URL.
 * Uses jsDelivr CDN — Twitter Twemoji (CC-BY 4.0).
 * Handles simple emoji, variation selectors, and ZWJ sequences.
 */
export function emojiToTwemojiUrl(emoji: string): string {
  const cps = [...emoji].map(c => c.codePointAt(0)!.toString(16));
  const hasZWJ = cps.includes("200d");
  const filtered = hasZWJ ? cps : cps.filter(cp => cp !== "fe0f");
  return `https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/${filtered.join("-")}.svg`;
}

/**
 * Local PNG overrides — downloaded from Twemoji CDN at 200×200.
 * These take priority over the CDN for all gift names listed here.
 */
export const GIFT_LOCAL_PNG: Record<string, string> = {
  // ── COMMON ────────────────────────────────────────────────────────────────
  "Яблоко":               "/gifts/emoji/1f34e.png",
  "Персик":               "/gifts/emoji/1f351.png",
  "Вишня":                "/gifts/emoji/1f352.png",
  "Виноград":             "/gifts/emoji/1f347.png",
  "Капкейк":              "/gifts/emoji/1f9c1.png",
  "Шоколад":              "/gifts/emoji/1f36b.png",
  "Печенье":              "/gifts/emoji/1f36a.png",
  "Арбуз":                "/gifts/emoji/1f349.png",
  "Тюльпан":              "/gifts/emoji/1f337.png",
  "Гибискус":             "/gifts/emoji/1f33a.png",
  "Пингвин":              "/gifts/emoji/1f427.png",
  "Щенок":                "/gifts/emoji/1f436.png",
  "Кролик":               "/gifts/emoji/1f430.png",
  "Хомячок":              "/gifts/emoji/1f439.png",
  "Пальма":               "/gifts/emoji/1f334.png",
  "Снежинка":             "/gifts/emoji/2744.png",
  "Осьминог":             "/gifts/emoji/1f419.png",
  "Краб":                 "/gifts/emoji/1f980.png",
  "Черепаха":             "/gifts/emoji/1f422.png",
  "Лягушка":              "/gifts/emoji/1f438.png",
  "Сердечко":             "/gifts/emoji/2764.png",
  "Звёздочка":            "/gifts/emoji/2b50.png",
  "Мыльный пузырь":       "/gifts/emoji/1fae7.png",
  "Конфета":              "/gifts/emoji/1f36c.png",
  "Клубника":             "/gifts/emoji/1f353.png",
  "Леденец":              "/gifts/emoji/1f36d.png",
  "Ромашка":              "/gifts/emoji/1f33c.png",
  "Цветок сакуры":        "/gifts/emoji/1f338.png",
  "Пончик":               "/gifts/emoji/1f369.png",
  "Мороженое":            "/gifts/emoji/1f366.png",
  "Рыбка":                "/gifts/emoji/1f41f.png",
  "Подсолнух":            "/gifts/emoji/1f33b.png",
  "Чашка кофе":           "/gifts/emoji/2615.png",
  "Луна":                 "/gifts/emoji/1f319.png",
  "Четырёхлистник":       "/gifts/emoji/1f340.png",
  "Бабочка":              "/gifts/emoji/1f98b.png",
  "Котёнок":              "/gifts/emoji/1f431.png",
  "Воздушный шар":        "/gifts/emoji/1f388.png",
  "Ретро-телефон":        "/gifts/emoji/1f4de.png",
  "Пицца":                "/gifts/emoji/1f355.png",
  "Медвежонок":           "/gifts/emoji/1f9f8.png",
  "Торт":                 "/gifts/emoji/1f382.png",
  "Игровая приставка":    "/gifts/emoji/1f3ae.png",
  "Снеговик":             "/gifts/emoji/26c4.png",
  "Радужный кит":         "/gifts/emoji/1f433.png",
  // ── RARE ──────────────────────────────────────────────────────────────────
  "Палитра":              "/gifts/emoji/1f3a8.png",
  "Пазл":                 "/gifts/emoji/1f9e9.png",
  "Мишень":               "/gifts/emoji/1f3af.png",
  "Барабаны":             "/gifts/emoji/1f941.png",
  "Пианино":              "/gifts/emoji/1f3b9.png",
  "Бант":                 "/gifts/emoji/1f380.png",
  "Волна":                "/gifts/emoji/1f30a.png",
  "Гора":                 "/gifts/emoji/1f3d4.png",
  "Свеча":                "/gifts/emoji/1f56f.png",
  "Маска":                "/gifts/emoji/1f3ad.png",
  "Жемчуг":               "/gifts/emoji/1faac.png",
  "Маяк":                 "/gifts/emoji/1f5fc.png",
  "Корона":               "/gifts/emoji/1f451.png",
  "Красная роза":         "/gifts/emoji/1f339.png",
  "Бриллиант":            "/gifts/emoji/1f48e.png",
  "Золотая монета":       "/gifts/emoji/1fa99.png",
  "Ракета":               "/gifts/emoji/1f680.png",
  "Гитара":               "/gifts/emoji/1f3b8.png",
  "Кубок":                "/gifts/emoji/1f3c6.png",
  "Радуга":               "/gifts/emoji/1f308.png",
  "Молния":               "/gifts/emoji/26a1.png",
  "Дельфин":              "/gifts/emoji/1f42c.png",
  "Лиса":                 "/gifts/emoji/1f98a.png",
  "Сова":                 "/gifts/emoji/1f989.png",
  "Акула":                "/gifts/emoji/1f988.png",
  "Парусник":             "/gifts/emoji/26f5.png",
  "Самоцвет":             "/gifts/emoji/1f3c5.png",
  "Медаль":               "/gifts/emoji/1f947.png",
  "Попугай":              "/gifts/emoji/1f99c.png",
  "Волшебная лампа":      "/gifts/emoji/1fa94.png",
  "Горящее сердце":       "/gifts/emoji/2764-fe0f-200d-1f525.png",
  // ── EPIC ──────────────────────────────────────────────────────────────────
  "Лев":                  "/gifts/emoji/1f981.png",
  "Тигр":                 "/gifts/emoji/1f42f.png",
  "Орёл":                 "/gifts/emoji/1f985.png",
  "Вулкан":               "/gifts/emoji/1f30b.png",
  "ДНК жизни":            "/gifts/emoji/1f9ec.png",
  "Фейерверк":            "/gifts/emoji/1f386.png",
  "Алхимия":              "/gifts/emoji/2697.png",
  "Горилла":              "/gifts/emoji/1f98d.png",
  "Пантера":              "/gifts/emoji/1f406.png",
  "Молот Тора":           "/gifts/emoji/1f528.png",
  "Паутина":              "/gifts/emoji/1f578.png",
  "Дракон":               "/gifts/emoji/1f409.png",
  "Единорог":             "/gifts/emoji/1f984.png",
  "Планета":              "/gifts/emoji/1fa90.png",
  "Волшебство":           "/gifts/emoji/1fa84.png",
  "Кристалл":             "/gifts/emoji/1f52e.png",
  "Пегас":                "/gifts/emoji/1f40e.png",
  "Нарвал":               "/gifts/emoji/1f40b.png",
  "Хрустальное сердце":   "/gifts/emoji/1f4a0.png",
  "Жар-птица":            "/gifts/emoji/1f525.png",
  "Грифон":               "/gifts/emoji/1f981.png",
  "Сапфировый кулон":     "/gifts/emoji/1f48e.png",
  "Магический гриб":      "/gifts/emoji/1f344.png",
  "Золотая рыбка":        "/gifts/emoji/1f41f.png",
  "Рубиновое кольцо":     "/gifts/emoji/1f48d.png",
  "Волшебная скрипка":    "/gifts/emoji/1f3bb.png",
  "Чёрный кот":           "/gifts/emoji/1f408-200d-2b1b.png",
  "Сфинкс":               "/gifts/emoji/1f3fa.png",
  "Огненный дракон":      "/gifts/emoji/1f432.png",
  // ── LEGENDARY ─────────────────────────────────────────────────────────────
  "Метеор":               "/gifts/emoji/1f320.png",
  "Планета Земля":        "/gifts/emoji/1f30d.png",
  "Вечный лёд":           "/gifts/emoji/1f9ca.png",
  "Магнит Судьбы":        "/gifts/emoji/1f9f2.png",
  "Атомный вихрь":        "/gifts/emoji/2622.png",
  "Алмазный скипетр":     "/gifts/emoji/1fa84.png",
  "Сапфировый щит":       "/gifts/emoji/1f6e1.png",
  "Галактика":            "/gifts/emoji/1f30c.png",
  "Ангел":                "/gifts/emoji/1f47c.png",
  "Пульс":                "/gifts/emoji/1f49c.png",
  "Легендарная звезда":   "/gifts/emoji/1f31f.png",
  // ── EXTRAS (keep legacy hand-crafted originals for some) ──────────────────
  "Морская звезда":        "/gifts/star-42.png",
  "Звёздная колесница":    "/gifts/star-small.png",
  "Корона Prime":          "/gifts/crown.png",
  "Пульс Сердца":          "/gifts/confetti-box.png",
  "Звезда Prime":          "/gifts/star-42.png",
  "Единый трон":           "/gifts/crown.png",
};
